#!/bin/bash

function outdated_branches {
  local result="$(git branch -av | grep -E '\[.*behind[^\]*]')"
  if [ "$result" ]
  then
    printf '\n%s\n' "$result"
  else
    printf ''
  fi
}

for d in *
do
  pushd $d > /dev/null && printf '\033[01;34m%s\033[0m: \033[01;33m%s\033[0m%s\n' "$(basename `pwd`)" "$(git symbolic-ref --short HEAD)" "$(outdated_branches)" && popd > /dev/null
done

